version: "2"

linters:
  enable:
    - errorlint
    - gocritic
    - gosec
    - misspell
    - modernize
    - nolintlint
    - paralleltest
    - predeclared
    - reassign
    - unconvert

formatters:
  enable:
    - gofumpt
