package pdq

import (
	"bytes"
	"context"
	"encoding/hex"
	"errors"
	"image"
	"image/color"
	"image/jpeg"
	"image/png"
	"math/bits"
	"testing"

	xdraw "golang.org/x/image/draw"
)

func TestHasherMatchesMetaImplementation(t *testing.T) {
	t.Parallel()

	result, err := New().Hash(t.Context(), encodePNG(t, patternedImage(96)))
	requireNoError(t, err)

	// Generated by the pinned Meta C++ implementation from the same image.
	expected := []string{
		"b5583108cffd7d1fc79c7d3c32cb828b7eda02f34fdaf518b000bb10f600b4a2",
		"891dc34dd69e29e814a4434c2be603cb29a15d1f2441435bffb0cbff12e1ccbf",
		"e00d9ba212a8d7b792cdd796671e28233b8fa8cb1a8f5fa2f55511ba23553e08",
		"dc4869e583cb834241f1e1e67eb3a9617c74f7b57114e9b1a8e5615547b46415",
		"b558cef747fd82e0c39882c332427d766e5afd8c4fda0af7a00044ef36006b5d",
		"e00d645d12a8284a92cd2869671ed7dc3b8f57361a8fa05df555ee452355c1f7",
		"a91f3cb2d69fd69f34a4bcb32be6fc342be1a2e02441bcf4ffb03c0013e13340",
		"dc48961883cb7cbd41f116197eb3569e7cf4084a7114160eaae59eaa57f499ea",
	}
	for orientation, expectedHex := range expected {
		expectedHash, decodeErr := hex.DecodeString(expectedHex)
		requireNoError(t, decodeErr)
		if !bytes.Equal(expectedHash, result.Hashes[orientation][:]) {
			t.Errorf("orientation %d: got %x, want %x", orientation, result.Hashes[orientation], expectedHash)
		}
	}
	if result.Quality != 100 {
		t.Errorf("quality: got %d, want 100", result.Quality)
	}
}

func TestHasherMatchesMetaJPEGImplementation(t *testing.T) {
	t.Parallel()

	result, err := New().Hash(t.Context(), encodeJPEG(t, patternedImage(96)))
	requireNoError(t, err)

	// JPEG decoders may differ slightly in IDCT and chroma upsampling; Meta's
	// Python regression suite also uses a Hamming tolerance of 16.
	expected := []string{
		"b5583108cffd7d1fc79c7d3c32cb868b7eda02f34fdaf508b000bb10f600d4a2",
		"a91dc34fd69e29e014a4434c2be603cb21a15d1f2440435fffb0c3ff12e1cebf",
		"e00d9ba293a8d7b59249d796671f28233b8fa8cb1a8f5fa2e55511aa63553e28",
		"fc4049e483cb834a41f1e9e67eb3896174b4f7b57114e9f18ae5695547b46415",
		"b558cef786f582e0c71c82c3324a7d766edafd1c4fda0af7300044ef36002b5d",
		"e00d645d92a8284a92492869671fd7dc3b8f57361a8fa05de555ee556355c1d7",
		"a91f3cb3d69ed69f34a4bdb32be6fc342be1a2e02441bce4ffb03c0013e13340",
		"fc48961a83cb7cb541f116197eb3769e74f4084a7115160aaae596aa47f49bea",
	}
	for orientation, expectedHex := range expected {
		expectedHash, decodeErr := hex.DecodeString(expectedHex)
		requireNoError(t, decodeErr)
		if distance := hammingDistance(result.Hashes[orientation][:], expectedHash); distance > 16 {
			t.Errorf("orientation %d: Hamming distance %d exceeds 16", orientation, distance)
		}
	}
	if result.Quality != 100 {
		t.Errorf("quality: got %d, want 100", result.Quality)
	}
}

func TestHasherDihedralHashesMatchRotatedImage(t *testing.T) {
	t.Parallel()

	source := patternedImage(96)
	original, err := New().Hash(t.Context(), encodePNG(t, source))
	requireNoError(t, err)

	rotated, err := New().Hash(t.Context(), encodePNG(t, rotate90Counterclockwise(source)))
	requireNoError(t, err)
	if original.Hashes[1] != rotated.Hashes[0] {
		t.Errorf("rotated hash: got %x, want %x", rotated.Hashes[0], original.Hashes[1])
	}
}

func TestHasherIgnoresPNGAlpha(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		size int
	}{
		{name: "without resize", size: 96},
		{name: "with resize", size: 600},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			opaque := patternedImage(test.size)
			transparent := image.NewNRGBA(opaque.Bounds())
			copy(transparent.Pix, opaque.Pix)
			for index := 3; index < len(transparent.Pix); index += 4 {
				transparent.Pix[index] = byte(index % 251)
			}

			hasher := New()
			opaqueResult, err := hasher.Hash(t.Context(), encodePNG(t, opaque))
			requireNoError(t, err)
			transparentResult, err := hasher.Hash(t.Context(), encodePNG(t, transparent))
			requireNoError(t, err)
			if opaqueResult != transparentResult {
				t.Errorf("transparent image result differs from opaque image result")
			}
		})
	}
}

func TestHasherNormalizesLargeImages(t *testing.T) {
	t.Parallel()

	source := patternedImage(512)
	large := image.NewNRGBA(image.Rect(0, 0, 1024, 1024))
	xdraw.CatmullRom.Scale(large, large.Bounds(), source, source.Bounds(), xdraw.Src, nil)

	hasher := New()
	sourceResult, err := hasher.Hash(t.Context(), encodePNG(t, source))
	requireNoError(t, err)
	largeResult, err := hasher.Hash(t.Context(), encodePNG(t, large))
	requireNoError(t, err)
	if distance := hammingDistance(sourceResult.Hashes[0][:], largeResult.Hashes[0][:]); distance > 31 {
		t.Errorf("Hamming distance %d exceeds 31", distance)
	}
	if sourceResult.Quality != largeResult.Quality {
		t.Errorf("quality: got %d, want %d", largeResult.Quality, sourceResult.Quality)
	}
}

func TestHashDimensions(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name           string
		width          int
		height         int
		expectedWidth  int
		expectedHeight int
	}{
		{name: "unchanged", width: 512, height: 320, expectedWidth: 512, expectedHeight: 320},
		{name: "landscape", width: 1600, height: 1004, expectedWidth: 512, expectedHeight: 321},
		{name: "portrait", width: 1004, height: 1600, expectedWidth: 321, expectedHeight: 512},
		{name: "square", width: 1024, height: 1024, expectedWidth: 512, expectedHeight: 512},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			width, height := hashDimensions(test.width, test.height)
			if width != test.expectedWidth || height != test.expectedHeight {
				t.Errorf(
					"hashDimensions(%d, %d) = (%d, %d), want (%d, %d)",
					test.width,
					test.height,
					width,
					height,
					test.expectedWidth,
					test.expectedHeight,
				)
			}
		})
	}
}

func TestHasherValidatesInput(t *testing.T) {
	t.Parallel()

	hasher := New()
	_, err := hasher.Hash(t.Context(), []byte("not an image"))
	if err == nil {
		t.Error("invalid image: expected an error")
	}

	ctx, cancel := context.WithCancel(t.Context())
	cancel()
	_, err = hasher.Hash(ctx, []byte("not reached"))
	if !errors.Is(err, context.Canceled) {
		t.Errorf("canceled context: got %v, want context.Canceled", err)
	}

	if err := validateDimensions(4_000, 4_000); err != nil {
		t.Errorf("valid dimensions: %v", err)
	}
	if err := validateDimensions(4_001, 4_000); err == nil {
		t.Error("oversized dimensions: expected an error")
	}
	if err := validateDimensions(0, 100); err == nil {
		t.Error("zero width: expected an error")
	}
}

func TestHasherReturnsZeroQualityForFlatImage(t *testing.T) {
	t.Parallel()

	flat := image.NewNRGBA(image.Rect(0, 0, 64, 64))
	result, err := New().Hash(t.Context(), encodeJPEG(t, flat))
	requireNoError(t, err)
	if result.Quality != 0 {
		t.Errorf("quality: got %d, want 0", result.Quality)
	}
}

func BenchmarkHasher512(b *testing.B) {
	imageBytes := encodePNG(b, patternedImage(512))
	hasher := New()
	b.ReportAllocs()
	b.ResetTimer()
	for b.Loop() {
		if _, err := hasher.Hash(b.Context(), imageBytes); err != nil {
			b.Fatal(err)
		}
	}
}

func patternedImage(size int) *image.NRGBA {
	result := image.NewNRGBA(image.Rect(0, 0, size, size))
	for y := range size {
		for x := range size {
			result.SetNRGBA(x, y, color.NRGBA{
				R: uint8((x*13 + y*3) % 256),
				G: uint8((x*x + y*7) % 256),
				B: uint8((x*5 + y*y) % 256),
				A: 0xff,
			})
		}
	}
	return result
}

func rotate90Counterclockwise(source *image.NRGBA) *image.NRGBA {
	bounds := source.Bounds()
	result := image.NewNRGBA(image.Rect(0, 0, bounds.Dy(), bounds.Dx()))
	for y := range bounds.Dy() {
		for x := range bounds.Dx() {
			result.SetNRGBA(y, bounds.Dx()-1-x, source.NRGBAAt(x, y))
		}
	}
	return result
}

func encodePNG(t testing.TB, source image.Image) []byte {
	t.Helper()
	var encoded bytes.Buffer
	requireNoError(t, png.Encode(&encoded, source))
	return encoded.Bytes()
}

func encodeJPEG(t testing.TB, source image.Image) []byte {
	t.Helper()
	var encoded bytes.Buffer
	requireNoError(t, jpeg.Encode(&encoded, source, nil))
	return encoded.Bytes()
}

func requireNoError(t testing.TB, err error) {
	t.Helper()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func hammingDistance(left, right []byte) int {
	distance := 0
	for index := range left {
		distance += bits.OnesCount8(left[index] ^ right[index])
	}
	return distance
}
